### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by justinkterry** [genyrosk/gym-chess#4]
Hey, I'm working with this library, and have forked them to made a few changes and would like to rerelease modified library as a part of the supplemental materials of a library I have going out.

For that to be fully legal, this code would have to be released under an open source license (currently it's under no license). An MIT license is the simplest and easiest to work with in terms of others reusing your code. Could you please add that to this library real quick to make the university IP lawyer happy?

**Comment by genyrosk** [comment]
Done ! #10 

Apologies for the delay 🙏
