### ISSUE TITLE
Env starting with only pawns, towers and king

### ISSUE THREAD

**Issue by isaacguerreir** [genyrosk/gym-chess#6]
The environment are starting with only the pawns, towers and king from both sides. How I could start with all the pieces in the game?

**Comment by Less97** [comment]
Same issue here.

**Comment by eisbetterthanpi** [comment]
In the file gym-chess/gym_chess/envs/chess.py
at line 212, edit the array for the chess board to something like this:
`                board = [['R1', 'N1', 'B1', 'K', 'Q', 'B2', 'N2', 'R2']]
                board += [['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8']]
                board += [['.']*8] * 4
                board += [['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8']]
                board += [['r1', 'n1', 'b1', 'k', 'q', 'b2', 'n2', 'r2']]`
?

**Comment by genyrosk** [comment]
Apologies for the silence, I haven't maintained this repo for a while 🙏 

The original code has been moved into the `v0` version, and I released a new `v1` version, which is an almost complete rewrite with some major improvements. I am also very close to releasing `v2`, which will use an engine built in Rust and gives a 100x boost in performance. 

Checkout the v1 version details: #8 
Follow the v2 version development: #9
